//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace BT.SaaS.IspssAdapter.BOS_API {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema/Ack")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema/Ack", IsNullable=false)]
    public partial class placeOrderResponse {
        
        private placeOrderResponseResponseHeader responseHeaderField;
        
        /// <remarks/>
        public placeOrderResponseResponseHeader responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema/Ack")]
    public partial class placeOrderResponseResponseHeader {
        
        private string pckField;
        
        private string callerIdField;
        
        private string genReturnCodeField;
        
        private string genReturnTextField;
        
        private string faultCategoryField;
        
        /// <remarks/>
        public string pck {
            get {
                return this.pckField;
            }
            set {
                this.pckField = value;
            }
        }
        
        /// <remarks/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <remarks/>
        public string genReturnCode {
            get {
                return this.genReturnCodeField;
            }
            set {
                this.genReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string genReturnText {
            get {
                return this.genReturnTextField;
            }
            set {
                this.genReturnTextField = value;
            }
        }
        
        /// <remarks/>
        public string faultCategory {
            get {
                return this.faultCategoryField;
            }
            set {
                this.faultCategoryField = value;
            }
        }
    }
}
