//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace BT.SaaS.MSEOAdapter
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets", IsNullable = false)]
    public partial class CustomerAssetsResponse
    {

        private customerAccountType customerAccountField;

        /// <remarks/>
        public customerAccountType customerAccount
        {
            get
            {
                return this.customerAccountField;
            }
            set
            {
                this.customerAccountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class customerAccountType
    {

        private productInstanceType[] productInstanceListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstance", IsNullable = false)]
        public productInstanceType[] productInstanceList
        {
            get
            {
                return this.productInstanceListField;
            }
            set
            {
                this.productInstanceListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class productInstanceType
    {

        private idType[] idField;

        private productNameType productNameField;

        private string customerIdField;

        private string statusField;

        private billingAccountType billingAccountField;

        private instanceIdentifierType instanceIdentifierField;

        private assetIdentifierTypeAssetIdentifier[] listOfAssetIdentifierField;

        private string serviceIdField;

        private string promotionIntegrationIdField;

        private string wLR3Field;

        private string supplierServiceIdField;

        private string servicePointIdField;

        private string assetDescriptionField;

        private System.DateTime cPIDateField;

        private bool cPIDateFieldSpecified;

        private System.DateTime effectiveStartDateField;

        private bool effectiveStartDateFieldSpecified;

        private System.DateTime effectiveEndDateField;

        private bool effectiveEndDateFieldSpecified;

        private System.DateTime contractStartDateField;

        private bool contractStartDateFieldSpecified;

        private System.DateTime contractEndDateField;

        private bool contractEndDateFieldSpecified;

        private string associationTypeField;

        private string hasComplexAssRelationshipField;

        private string inComplexAssRelationshipField;

        private string extensionNumberField;

        private string primaryAssetField;

        private string quantityField;

        private string assignmentStatusField;

        private string productIdentifierField;

        private string customerFriendlyNameField;

        private string assetNumberField;

        private string installationPostcodeField;

        private string broadbandPromotionNameField;

        private string broadbandPromotionScodeField;

        private LinkedAssetType[] listofAssetInRelationshipField;

        private AssetHasRelationshipType[] listofAssetHasRelationshipField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private string promotionalScodeField;

        private string priceTypeField;

        private string productFulfillmentTypeField;

        private string serviceTypeField;

        private string serviceAccountIdField;

        private string offerPromotionIdField;

        private string previousOfferPromotionIdField;

        private string basePromotionIdField;

        private string previousBasePromotionIdField;

        private string tBYBPromotionIdField;

        private string previousTBYBPromotionIdField;

        private string accountConsolidatedTypeField;

        private addressDetailsType[] addressListField;

        private string benefitPromIntegIdField;

        private string markerIntegIdField;

        private System.DateTime createdDateField;

        private bool createdDateFieldSpecified;

        private System.DateTime ceasedDateField;

        private bool ceasedDateFieldSpecified;

        private string cPEReturnStateField;

        private string supplierProductCodeField;

        private string oFCOMSpeedCOP2Field;

        private string oFCOMSpeedCOPRightToExitEligibilityField;

        private string dealerChannelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public idType[] id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public productNameType productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public billingAccountType billingAccount
        {
            get
            {
                return this.billingAccountField;
            }
            set
            {
                this.billingAccountField = value;
            }
        }

        /// <remarks/>
        public instanceIdentifierType instanceIdentifier
        {
            get
            {
                return this.instanceIdentifierField;
            }
            set
            {
                this.instanceIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("assetIdentifier", IsNullable = false)]
        public assetIdentifierTypeAssetIdentifier[] ListOfAssetIdentifier
        {
            get
            {
                return this.listOfAssetIdentifierField;
            }
            set
            {
                this.listOfAssetIdentifierField = value;
            }
        }

        /// <remarks/>
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }

        /// <remarks/>
        public string promotionIntegrationId
        {
            get
            {
                return this.promotionIntegrationIdField;
            }
            set
            {
                this.promotionIntegrationIdField = value;
            }
        }

        /// <remarks/>
        public string WLR3
        {
            get
            {
                return this.wLR3Field;
            }
            set
            {
                this.wLR3Field = value;
            }
        }

        /// <remarks/>
        public string SupplierServiceId
        {
            get
            {
                return this.supplierServiceIdField;
            }
            set
            {
                this.supplierServiceIdField = value;
            }
        }

        /// <remarks/>
        public string ServicePointId
        {
            get
            {
                return this.servicePointIdField;
            }
            set
            {
                this.servicePointIdField = value;
            }
        }

        /// <remarks/>
        public string assetDescription
        {
            get
            {
                return this.assetDescriptionField;
            }
            set
            {
                this.assetDescriptionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CPIDate
        {
            get
            {
                return this.cPIDateField;
            }
            set
            {
                this.cPIDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CPIDateSpecified
        {
            get
            {
                return this.cPIDateFieldSpecified;
            }
            set
            {
                this.cPIDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime EffectiveStartDate
        {
            get
            {
                return this.effectiveStartDateField;
            }
            set
            {
                this.effectiveStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveStartDateSpecified
        {
            get
            {
                return this.effectiveStartDateFieldSpecified;
            }
            set
            {
                this.effectiveStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime EffectiveEndDate
        {
            get
            {
                return this.effectiveEndDateField;
            }
            set
            {
                this.effectiveEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveEndDateSpecified
        {
            get
            {
                return this.effectiveEndDateFieldSpecified;
            }
            set
            {
                this.effectiveEndDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime ContractStartDate
        {
            get
            {
                return this.contractStartDateField;
            }
            set
            {
                this.contractStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractStartDateSpecified
        {
            get
            {
                return this.contractStartDateFieldSpecified;
            }
            set
            {
                this.contractStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime ContractEndDate
        {
            get
            {
                return this.contractEndDateField;
            }
            set
            {
                this.contractEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractEndDateSpecified
        {
            get
            {
                return this.contractEndDateFieldSpecified;
            }
            set
            {
                this.contractEndDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string AssociationType
        {
            get
            {
                return this.associationTypeField;
            }
            set
            {
                this.associationTypeField = value;
            }
        }

        /// <remarks/>
        public string HasComplexAssRelationship
        {
            get
            {
                return this.hasComplexAssRelationshipField;
            }
            set
            {
                this.hasComplexAssRelationshipField = value;
            }
        }

        /// <remarks/>
        public string InComplexAssRelationship
        {
            get
            {
                return this.inComplexAssRelationshipField;
            }
            set
            {
                this.inComplexAssRelationshipField = value;
            }
        }

        /// <remarks/>
        public string ExtensionNumber
        {
            get
            {
                return this.extensionNumberField;
            }
            set
            {
                this.extensionNumberField = value;
            }
        }

        /// <remarks/>
        public string PrimaryAsset
        {
            get
            {
                return this.primaryAssetField;
            }
            set
            {
                this.primaryAssetField = value;
            }
        }

        /// <remarks/>
        public string quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string assignmentStatus
        {
            get
            {
                return this.assignmentStatusField;
            }
            set
            {
                this.assignmentStatusField = value;
            }
        }

        /// <remarks/>
        public string ProductIdentifier
        {
            get
            {
                return this.productIdentifierField;
            }
            set
            {
                this.productIdentifierField = value;
            }
        }

        /// <remarks/>
        public string customerFriendlyName
        {
            get
            {
                return this.customerFriendlyNameField;
            }
            set
            {
                this.customerFriendlyNameField = value;
            }
        }

        /// <remarks/>
        public string assetNumber
        {
            get
            {
                return this.assetNumberField;
            }
            set
            {
                this.assetNumberField = value;
            }
        }

        /// <remarks/>
        public string installationPostcode
        {
            get
            {
                return this.installationPostcodeField;
            }
            set
            {
                this.installationPostcodeField = value;
            }
        }

        /// <remarks/>
        public string broadbandPromotionName
        {
            get
            {
                return this.broadbandPromotionNameField;
            }
            set
            {
                this.broadbandPromotionNameField = value;
            }
        }

        /// <remarks/>
        public string broadbandPromotionScode
        {
            get
            {
                return this.broadbandPromotionScodeField;
            }
            set
            {
                this.broadbandPromotionScodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LinkedAsset", IsNullable = false)]
        public LinkedAssetType[] ListofAssetInRelationship
        {
            get
            {
                return this.listofAssetInRelationshipField;
            }
            set
            {
                this.listofAssetInRelationshipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LinkedAsset", IsNullable = false)]
        public AssetHasRelationshipType[] ListofAssetHasRelationship
        {
            get
            {
                return this.listofAssetHasRelationshipField;
            }
            set
            {
                this.listofAssetHasRelationshipField = value;
            }
        }

        /// <remarks/>
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PromotionalScode
        {
            get
            {
                return this.promotionalScodeField;
            }
            set
            {
                this.promotionalScodeField = value;
            }
        }

        /// <remarks/>
        public string priceType
        {
            get
            {
                return this.priceTypeField;
            }
            set
            {
                this.priceTypeField = value;
            }
        }

        /// <remarks/>
        public string productFulfillmentType
        {
            get
            {
                return this.productFulfillmentTypeField;
            }
            set
            {
                this.productFulfillmentTypeField = value;
            }
        }

        /// <remarks/>
        public string serviceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }

        /// <remarks/>
        public string serviceAccountId
        {
            get
            {
                return this.serviceAccountIdField;
            }
            set
            {
                this.serviceAccountIdField = value;
            }
        }

        /// <remarks/>
        public string offerPromotionId
        {
            get
            {
                return this.offerPromotionIdField;
            }
            set
            {
                this.offerPromotionIdField = value;
            }
        }

        /// <remarks/>
        public string previousOfferPromotionId
        {
            get
            {
                return this.previousOfferPromotionIdField;
            }
            set
            {
                this.previousOfferPromotionIdField = value;
            }
        }

        /// <remarks/>
        public string basePromotionId
        {
            get
            {
                return this.basePromotionIdField;
            }
            set
            {
                this.basePromotionIdField = value;
            }
        }

        /// <remarks/>
        public string previousBasePromotionId
        {
            get
            {
                return this.previousBasePromotionIdField;
            }
            set
            {
                this.previousBasePromotionIdField = value;
            }
        }

        /// <remarks/>
        public string TBYBPromotionId
        {
            get
            {
                return this.tBYBPromotionIdField;
            }
            set
            {
                this.tBYBPromotionIdField = value;
            }
        }

        /// <remarks/>
        public string previousTBYBPromotionId
        {
            get
            {
                return this.previousTBYBPromotionIdField;
            }
            set
            {
                this.previousTBYBPromotionIdField = value;
            }
        }

        /// <remarks/>
        public string accountConsolidatedType
        {
            get
            {
                return this.accountConsolidatedTypeField;
            }
            set
            {
                this.accountConsolidatedTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("addressDetail", IsNullable = false)]
        public addressDetailsType[] addressList
        {
            get
            {
                return this.addressListField;
            }
            set
            {
                this.addressListField = value;
            }
        }

        /// <remarks/>
        public string benefitPromIntegId
        {
            get
            {
                return this.benefitPromIntegIdField;
            }
            set
            {
                this.benefitPromIntegIdField = value;
            }
        }

        /// <remarks/>
        public string markerIntegId
        {
            get
            {
                return this.markerIntegIdField;
            }
            set
            {
                this.markerIntegIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdDateSpecified
        {
            get
            {
                return this.createdDateFieldSpecified;
            }
            set
            {
                this.createdDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime ceasedDate
        {
            get
            {
                return this.ceasedDateField;
            }
            set
            {
                this.ceasedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ceasedDateSpecified
        {
            get
            {
                return this.ceasedDateFieldSpecified;
            }
            set
            {
                this.ceasedDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CPEReturnState
        {
            get
            {
                return this.cPEReturnStateField;
            }
            set
            {
                this.cPEReturnStateField = value;
            }
        }

        /// <remarks/>
        public string supplierProductCode
        {
            get
            {
                return this.supplierProductCodeField;
            }
            set
            {
                this.supplierProductCodeField = value;
            }
        }

        /// <remarks/>
        public string OFCOMSpeedCOP2
        {
            get
            {
                return this.oFCOMSpeedCOP2Field;
            }
            set
            {
                this.oFCOMSpeedCOP2Field = value;
            }
        }

        /// <remarks/>
        public string OFCOMSpeedCOPRightToExitEligibility
        {
            get
            {
                return this.oFCOMSpeedCOPRightToExitEligibilityField;
            }
            set
            {
                this.oFCOMSpeedCOPRightToExitEligibilityField = value;
            }
        }

        /// <remarks/>
        public string dealerChannel
        {
            get
            {
                return this.dealerChannelField;
            }
            set
            {
                this.dealerChannelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class idType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class addressDetailsType
    {

        private string addressIdentifierField;

        private string addressNameField;

        private string countryField;

        private string postCodeField;

        private string postTownField;

        private string countyField;

        private string buildingNameField;

        private string subBuildingNameField;

        private string buildingNumberField;

        private string thoroughfareNameField;

        private string localityField;

        private string poBoxField;

        private string dependentThoroughfareDescriptorField;

        private string doubleDependentLocalityField;

        private string provinceField;

        private string bTcherisedNameField;

        /// <remarks/>
        public string addressIdentifier
        {
            get
            {
                return this.addressIdentifierField;
            }
            set
            {
                this.addressIdentifierField = value;
            }
        }

        /// <remarks/>
        public string addressName
        {
            get
            {
                return this.addressNameField;
            }
            set
            {
                this.addressNameField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string postCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }

        /// <remarks/>
        public string postTown
        {
            get
            {
                return this.postTownField;
            }
            set
            {
                this.postTownField = value;
            }
        }

        /// <remarks/>
        public string county
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }

        /// <remarks/>
        public string buildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }

        /// <remarks/>
        public string subBuildingName
        {
            get
            {
                return this.subBuildingNameField;
            }
            set
            {
                this.subBuildingNameField = value;
            }
        }

        /// <remarks/>
        public string buildingNumber
        {
            get
            {
                return this.buildingNumberField;
            }
            set
            {
                this.buildingNumberField = value;
            }
        }

        /// <remarks/>
        public string thoroughfareName
        {
            get
            {
                return this.thoroughfareNameField;
            }
            set
            {
                this.thoroughfareNameField = value;
            }
        }

        /// <remarks/>
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }

        /// <remarks/>
        public string poBox
        {
            get
            {
                return this.poBoxField;
            }
            set
            {
                this.poBoxField = value;
            }
        }

        /// <remarks/>
        public string dependentThoroughfareDescriptor
        {
            get
            {
                return this.dependentThoroughfareDescriptorField;
            }
            set
            {
                this.dependentThoroughfareDescriptorField = value;
            }
        }

        /// <remarks/>
        public string doubleDependentLocality
        {
            get
            {
                return this.doubleDependentLocalityField;
            }
            set
            {
                this.doubleDependentLocalityField = value;
            }
        }

        /// <remarks/>
        public string Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        /// <remarks/>
        public string BTcherisedName
        {
            get
            {
                return this.bTcherisedNameField;
            }
            set
            {
                this.bTcherisedNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class AssetHasRelationshipType
    {

        private string relationshipTypeField;

        private string activeFlagField;

        private string integrationIdField;

        private string scodeField;

        private string productNameField;

        private string primaryAssetFlagField;

        private string serviceIdField;

        /// <remarks/>
        public string RelationshipType
        {
            get
            {
                return this.relationshipTypeField;
            }
            set
            {
                this.relationshipTypeField = value;
            }
        }

        /// <remarks/>
        public string ActiveFlag
        {
            get
            {
                return this.activeFlagField;
            }
            set
            {
                this.activeFlagField = value;
            }
        }

        /// <remarks/>
        public string IntegrationId
        {
            get
            {
                return this.integrationIdField;
            }
            set
            {
                this.integrationIdField = value;
            }
        }

        /// <remarks/>
        public string Scode
        {
            get
            {
                return this.scodeField;
            }
            set
            {
                this.scodeField = value;
            }
        }

        /// <remarks/>
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        public string PrimaryAssetFlag
        {
            get
            {
                return this.primaryAssetFlagField;
            }
            set
            {
                this.primaryAssetFlagField = value;
            }
        }

        /// <remarks/>
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class LinkedAssetType
    {

        private string relationshipTypeField;

        private string activeFlagField;

        private string integrationIdField;

        private string scodeField;

        private string productNameField;

        private string primaryAssetFlagField;

        private string serviceIdField;

        /// <remarks/>
        public string RelationshipType
        {
            get
            {
                return this.relationshipTypeField;
            }
            set
            {
                this.relationshipTypeField = value;
            }
        }

        /// <remarks/>
        public string ActiveFlag
        {
            get
            {
                return this.activeFlagField;
            }
            set
            {
                this.activeFlagField = value;
            }
        }

        /// <remarks/>
        public string IntegrationId
        {
            get
            {
                return this.integrationIdField;
            }
            set
            {
                this.integrationIdField = value;
            }
        }

        /// <remarks/>
        public string Scode
        {
            get
            {
                return this.scodeField;
            }
            set
            {
                this.scodeField = value;
            }
        }

        /// <remarks/>
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        public string PrimaryAssetFlag
        {
            get
            {
                return this.primaryAssetFlagField;
            }
            set
            {
                this.primaryAssetFlagField = value;
            }
        }

        /// <remarks/>
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class instanceIdentifierType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class billingAccountSystemType
    {

        private string nameField;

        private string instanceField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class billingAccountSubStatusType
    {

        private string codeField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class billingAccountStatusType
    {

        private billingAccountSubStatusType billingAccountSubStatusField;

        private string codeField;

        /// <remarks/>
        public billingAccountSubStatusType billingAccountSubStatus
        {
            get
            {
                return this.billingAccountSubStatusField;
            }
            set
            {
                this.billingAccountSubStatusField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class billingAccountType
    {

        private string accountNumberField;

        private System.DateTime billingAccountCeasedDateField;

        private bool billingAccountCeasedDateFieldSpecified;

        private billingAccountStatusType billingAccountStatusField;

        private billingAccountSystemType billingAccountSystemField;

        private string typeField;

        /// <remarks/>
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime billingAccountCeasedDate
        {
            get
            {
                return this.billingAccountCeasedDateField;
            }
            set
            {
                this.billingAccountCeasedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool billingAccountCeasedDateSpecified
        {
            get
            {
                return this.billingAccountCeasedDateFieldSpecified;
            }
            set
            {
                this.billingAccountCeasedDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public billingAccountStatusType billingAccountStatus
        {
            get
            {
                return this.billingAccountStatusField;
            }
            set
            {
                this.billingAccountStatusField = value;
            }
        }

        /// <remarks/>
        public billingAccountSystemType billingAccountSystem
        {
            get
            {
                return this.billingAccountSystemField;
            }
            set
            {
                this.billingAccountSystemField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class identifierType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class productNameType
    {

        private string nameField;

        private string codeField;

        private identifierType identifierField;

        private string familyField;

        private string productTypeField;

        private string bundleFlagField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public identifierType identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        public string family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        public string productType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        /// <remarks/>
        public string bundleFlag
        {
            get
            {
                return this.bundleFlagField;
            }
            set
            {
                this.bundleFlagField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://capabilities.nat.bt.com/xsd/crm/v9/Assets")]
    public partial class assetIdentifierTypeAssetIdentifier
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
