//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace BT.SaaS.IspssAdapter.GetVasUsage {
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "getVasUsageSoap", Namespace = "http://tempuri.org/")]
    public partial class SdpGetVasUsageService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        public SdpGetVasUsageService(string url)
        {
            this.Url = url;
        }
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://business-services-sync-api/v2.1.0.1/getVASUsage", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getVASUsageResponse", Namespace = "http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
        public GetVASUsageResponseType getVasUsage([System.Xml.Serialization.XmlElementAttribute("getVASUsage", Namespace = "http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")] GetVASUsageType getVASUsage1)
        {
            object[] results = this.Invoke("getVasUsage", new object[] {
                    getVASUsage1});
            return ((GetVASUsageResponseType)(results[0]));
        }

    }
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    [System.Xml.Serialization.XmlRootAttribute("getVASUsage", Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema", IsNullable=false)]
    public partial class GetVASUsageType {
        
        private RequestHeaderType requestHeaderField;
        
        private string bESServiceAccountIdField;
        
        private string productInstanceIdField;
        
        private string tariffIdField;
        
        private string tierProductIdField;
        
        private string productCodeField;
        
        /// <remarks/>
        public RequestHeaderType requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        public string BESServiceAccountId {
            get {
                return this.bESServiceAccountIdField;
            }
            set {
                this.bESServiceAccountIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductInstanceId {
            get {
                return this.productInstanceIdField;
            }
            set {
                this.productInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public string TariffId {
            get {
                return this.tariffIdField;
            }
            set {
                this.tariffIdField = value;
            }
        }
        
        /// <remarks/>
        public string TierProductId {
            get {
                return this.tierProductIdField;
            }
            set {
                this.tierProductIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public partial class RequestHeaderType {
        
        private string pckField;
        
        private long callerIdField;
        
        private string callerUserIdField;
        
        private string callerPasswordField;
        
        private string linkUserIdField;
        
        private string linkPasswordField;
        
        /// <remarks/>
        public string pck {
            get {
                return this.pckField;
            }
            set {
                this.pckField = value;
            }
        }
        
        /// <remarks/>
        public long callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <remarks/>
        public string callerUserId {
            get {
                return this.callerUserIdField;
            }
            set {
                this.callerUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string callerPassword {
            get {
                return this.callerPasswordField;
            }
            set {
                this.callerPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string linkUserId {
            get {
                return this.linkUserIdField;
            }
            set {
                this.linkUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string linkPassword {
            get {
                return this.linkPasswordField;
            }
            set {
                this.linkPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public partial class ServicedByType {
        
        private string nameField;
        
        private string versionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public partial class DatabaseFaultType {
        
        private string procedureField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        private string tableField;
        
        private string columnField;
        
        /// <remarks/>
        public string procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
            }
        }
        
        /// <remarks/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        public string column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public partial class FaultDetailType {
        
        private string descriptionField;
        
        private string methodField;
        
        private string faultAttributeNameField;
        
        private string faultAttributeValueField;
        
        private DatabaseFaultType databaseField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public string faultAttributeName {
            get {
                return this.faultAttributeNameField;
            }
            set {
                this.faultAttributeNameField = value;
            }
        }
        
        /// <remarks/>
        public string faultAttributeValue {
            get {
                return this.faultAttributeValueField;
            }
            set {
                this.faultAttributeValueField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseFaultType database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public partial class ResponseHeaderType {
        
        private string pckField;
        
        private long callerIdField;
        
        private long genReturnCodeField;
        
        private string genReturnTextField;
        
        private FaultCategoryType faultCategoryField;
        
        private bool faultCategoryFieldSpecified;
        
        private FaultDetailType faultDetailField;
        
        private ServicedByType[] listOfServicedByField;
        
        /// <remarks/>
        public string pck {
            get {
                return this.pckField;
            }
            set {
                this.pckField = value;
            }
        }
        
        /// <remarks/>
        public long callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <remarks/>
        public long genReturnCode {
            get {
                return this.genReturnCodeField;
            }
            set {
                this.genReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string genReturnText {
            get {
                return this.genReturnTextField;
            }
            set {
                this.genReturnTextField = value;
            }
        }
        
        /// <remarks/>
        public FaultCategoryType faultCategory {
            get {
                return this.faultCategoryField;
            }
            set {
                this.faultCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool faultCategorySpecified {
            get {
                return this.faultCategoryFieldSpecified;
            }
            set {
                this.faultCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FaultDetailType faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("servicedBy", IsNullable=false)]
        public ServicedByType[] listOfServicedBy {
            get {
                return this.listOfServicedByField;
            }
            set {
                this.listOfServicedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    public enum FaultCategoryType {
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        Infrastructure,
        
        /// <remarks/>
        Timeout,
        
        /// <remarks/>
        System,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema")]
    [System.Xml.Serialization.XmlRootAttribute("getVASUsageResponse", Namespace="http://iat.intra.btexact.com/sysdesign/R7.1/ISPSchema", IsNullable=false)]
    public partial class GetVASUsageResponseType {
        
        private ResponseHeaderType responseHeaderField;
        
        private string totalQuantityField;
        
        private string freeQuantityField;
        
        /// <remarks/>
        public ResponseHeaderType responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotalQuantity {
            get {
                return this.totalQuantityField;
            }
            set {
                this.totalQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FreeQuantity {
            get {
                return this.freeQuantityField;
            }
            set {
                this.freeQuantityField = value;
            }
        }
    }
}
